# -*- coding: utf-8 -*-
"""Data_Preprocessing_Only_TEST3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pAK5knBiv0yaAo6CE051xA1ajSzUiIs
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("titanic.csv")

print("Dataset Shape:", df.shape)

print("\nMissing Values Before Cleaning")
print(df.isnull().sum())

df.drop_duplicates(inplace=True)

df["Age"].fillna(df["Age"].median(), inplace=True)
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

df.drop("Cabin", axis=1, inplace=True)

df.drop(
    ["PassengerId", "Name", "Ticket"],
    axis=1,
    inplace=True
)

df = pd.get_dummies(
    df,
    columns=["Sex", "Embarked"],
    drop_first=True
)

X = df.drop("Survived", axis=1)
y = df["Survived"]

scaler = StandardScaler()

X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

models = {
    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "KNN":
        KNeighborsClassifier(n_neighbors=5),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=100,
            random_state=42
        )
}

result = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    pre = precision_score(y_test, y_pred)

    rec = recall_score(y_test, y_pred)

    f1 = f1_score(y_test, y_pred)

    cm = confusion_matrix(y_test, y_pred)

    print("\n")
    print("=" * 50)
    print(name)
    print("=" * 50)

    print("Accuracy :", round(acc, 4))
    print("Precision:", round(pre, 4))
    print("Recall   :", round(rec, 4))
    print("F1 Score :", round(f1, 4))

    print("\nConfusion Matrix")
    print(cm)

    result.append(
        [name, acc, pre, rec, f1]
    )

comparison = pd.DataFrame(
    result,
    columns=[
        "Algorithm",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

print("\n")
print("=" * 50)
print("MODEL COMPARISON")
print("=" * 50)

print(
    comparison.sort_values(
        by="Accuracy",
        ascending=False
    )
)

